### ISSUE TITLE
add run duration

### ISSUE THREAD

**Issue by noahdietz** [30x/khaos-monkey#8]
If we add a configurable value for a khaos duration, this pod could be run as a [Scheduled Job](http://kubernetes.io/docs/user-guide/scheduled-jobs/), which was a suggested deployment style by folks on Twitter.

I think this is a good idea, yet another thing you can set up and it just works.

Thoughts?

**Comment by noahdietz** [comment]
implemented this [here](https://github.com/30x/khaos-monkey/pull/7/commits/28ce85bc123b8560f9161541621844de6e9cffc3)

**Comment by jbowen93** [comment]
I think this is a good idea however I'll suggest something a little more specific. One of the original goals of the NOSS chaos monkey was to only run it during working hours. That is, it doesn't run on weekends, holidays, or outside of 9-5. This definitely falls under a quality of life feature but I think it's relatively important since nobody wants to be creating late night P1s for themselves. 

I'll create a separate issue for this.

**Comment by noahdietz** [comment]
conversation moved [here](https://github.com/30x/khaos-monkey/issues/9). Closing
